/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import labyrinth.Labyrinth;

/**
 *
 * @author marek
 */
public class GuiF extends javax.swing.JFrame {

    public  MenuP menu;
    public GameP board;
    public LoadGameP LoadGame;
    public SaveGameP SaveGame;
    
    /**
     * Creates new form MenuGui
     */
    public GuiF() {
        
        this.setVisible(true);
        initComponents();

        displayMenu();
           
        pack();
    }
    
    public void reDrawBoard() {
        board.setVisible(false);
        board.removeAll();
        board = new GameP();
        this.add(board);
    }
    
    public void displayBoard() {
        board = new GameP();
        this.add(board);
    }
    
    public void hideMenu() {
        menu.setVisible(false);
    }
    
    public void displayMenu() {
        menu = new MenuP();
        this.add(menu);
    }
    
    
    
    public void DisplayLoadGame()
    {
        LoadGame = new LoadGameP();
        menu.setVisible(false);
        this.add(LoadGame);
        pack();
    }
    
    public void DisplaySaveGame()
    {
        SaveGame = new SaveGameP();
        menu.setVisible(false);
        this.add(SaveGame);
        pack();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        jFileChooser3 = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileM = new javax.swing.JMenu();
        LoadGameMI = new javax.swing.JMenuItem();
        SaveGameMI = new javax.swing.JMenuItem();
        ExitGameMI = new javax.swing.JMenuItem();
        EditM = new javax.swing.JMenu();
        UndoMI = new javax.swing.JMenuItem();

        jFileChooser3.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        FileM.setText("File");

        LoadGameMI.setText("Load Game");
        LoadGameMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGameMIActionPerformed(evt);
            }
        });
        FileM.add(LoadGameMI);

        SaveGameMI.setText("Save Game");
        SaveGameMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveGameMIActionPerformed(evt);
            }
        });
        FileM.add(SaveGameMI);

        ExitGameMI.setText("Exit Game");
        ExitGameMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitGameMIActionPerformed(evt);
            }
        });
        FileM.add(ExitGameMI);

        jMenuBar1.add(FileM);

        EditM.setText("Edit");

        UndoMI.setText("Undo");
        UndoMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoMIActionPerformed(evt);
            }
        });
        EditM.add(UndoMI);

        jMenuBar1.add(EditM);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void LoadGameMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGameMIActionPerformed
        // TODO add your handling code here:
        System.out.println("Load Game");
        DisplayLoadGame();
    }//GEN-LAST:event_LoadGameMIActionPerformed

    private void ExitGameMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitGameMIActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitGameMIActionPerformed

    private void SaveGameMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveGameMIActionPerformed
        // TODO add your handling code here:
        System.out.println("Save Game");
        DisplaySaveGame();
    }//GEN-LAST:event_SaveGameMIActionPerformed

    private void UndoMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoMIActionPerformed
        // TODO add your handling code here:
        System.out.println("Undo");
        Labyrinth.restoreMove();
        reDrawBoard();
    }//GEN-LAST:event_UndoMIActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EditM;
    private javax.swing.JMenuItem ExitGameMI;
    private javax.swing.JMenu FileM;
    private javax.swing.JMenuItem LoadGameMI;
    private javax.swing.JMenuItem SaveGameMI;
    private javax.swing.JMenuItem UndoMI;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
