#!/bin/bash

wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/GREEN1.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/BLUE1.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/iLR.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/iUD.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/RED1.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/rohLD.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/rohLU.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/rohRD.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/rohRU.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s1.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s2.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s3.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s4.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s5.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s6.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s7.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s8.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s9.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s10.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s11.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s12.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s13.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s14.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s15.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s16.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s17.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s18.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s19.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s20.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s21.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s22.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s23.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/s24.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/title2.gif
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/Title.gif
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/tLRD.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/tLRU.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/tLUD.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/tRUD.png
wget -P ./media http://www.stud.fit.vutbr.cz/~xmatus29/IJA/YELLOW1.png

